% Study Reccomendation Expert System

:- dynamic fact/2.

% Fact representation
% fact(Student, Trait).
% Example:
% fact(student1, forgets_quickly).

% Helper predicate to check if a student has a given trait.
% This improves readability in the rules below.
has(Student, Trait) :- fact(Student, Trait).

% Rule 1:
% If a student forgets information quickly and is preparing
% for exams, recommend Active Recall as a study technique.
recommend(Student, active_recall) :-
    has(Student, forgets_quickly),
    has(Student, preparing_for_exams).


% Rule 2:
% If a student wants long-term retention and is studying
% a large volume of content, recommend Spaced Repetition.
recommend(Student, spaced_repetition) :-
    has(Student, wants_long_term_retention),
    has(Student, studying_large_content).


% Rule 3:
% If a student learns effectively by explaining concepts
% to others, recommend the Feynman Technique.
recommend(Student, feynman_technique) :-
    has(Student, learns_by_explaining).


% Rule 4:
% If a student prefers visual learning and likes diagrams
% or structured notes, recommend Mind Mapping.
recommend(Student, mind_mapping) :-
    has(Student, prefers_visual_learning),
    has(Student, likes_diagrams).


% Rule 5:
% If a student is studying a practical or problem-solving
% course (e.g., mathematics, engineering, programming),
% recommend Practice-Based Learning.
recommend(Student, practice_based_learning) :-
    has(Student, studying_practical_course).


% Rule 6:
% If a student prefers structured study schedules and
% studies independently, recommend creating a Personal
% Study Timetable to organise their learning.
recommend(Student, personal_study_timetable) :-
    has(Student, prefers_organized_schedule),
    has(Student, studies_alone).


% Rule 7:
% If a student gets bored reading textbooks but prefers
% engaging learning approaches, recommend Active Recall.
recommend(Student, active_recall) :-
    has(Student, bored_reading_textbooks),
    has(Student, wants_engaging_methods).


% Rule 8:
% If a student finds traditional reading boring but prefers
% more interactive learning, recommend solving Practice Questions.
recommend(Student, practice_questions) :-
    has(Student, bored_reading_textbooks),
    has(Student, wants_engaging_methods).


% Rule 9:
% If a student tends to procrastinate and is easily distracted,
% recommend the Pomodoro Technique for better time management.
recommend(Student, pomodoro_technique) :-
    has(Student, procrastinates),
    has(Student, easily_distracted).


% Rule 10:
% If a student is easily distracted, also recommend creating
% a distraction-free study environment.
recommend(Student, distraction_free_environment) :-
    has(Student, easily_distracted).


% Rule 11:
% If a student prefers discussions and collaborative learning,
% recommend Group Study sessions.
recommend(Student, group_study) :-
    has(Student, prefers_discussion),
    has(Student, collaborative_learner).


% Rule 12:
% If a student struggles with complex topics, recommend the
% Feynman Technique to improve conceptual understanding.
recommend(Student, feynman_technique) :-
    has(Student, difficulty_with_complex_topics).


% Rule 13:
% If a student struggles with complex topics, Mind Mapping
% can also help simplify and organise information visually.
recommend(Student, mind_mapping) :-
    has(Student, difficulty_with_complex_topics).


% Recommendation Aggregation
% This predicate gathers all recommendations generated by
% the inference rules and returns them as a unique list.

% setof/3 collects all unique recommendations R that satisfy
% the recommend(Student, R) predicate.
recommendations(Student, List) :-
    setof(R, recommend(Student, R), List), !.

% If no recommendation rules match, return an empty list instead of failing.
recommendations(_, []).